kind: pipeline
type: exec
name: default

steps:
  - name: create
    image: earthly/earthly:v0.6.20
    privileged: true
    commands:
      - git submodule update --init --recursive
      - earthly +run
