kind: pipeline
type: docker
name: default

steps:
  - name: create
    image: earthly/earthly
    commands:
      - /usr/bin/earthly-entrypoint.sh
      - git submodule update --init --recursive
      - earthly +run
