baseURL: "https://blog.robnarok.de"
languageCode: "de-de"
title: "blog.robnarok.de"
paginate: 5
theme: m10c
params:
    author: "Robnarok"
    description: "Irgendso ein Typ, der jetzt einen Blog im Internet hat"
    menu_item_separator: "/"
    avatar: "picture.jpg"
    social:
      - icon: "github"
        name: "Mein Github"
        url: "https://github.com/robnarok"
    style:
        darkestColor: '#2e3440'
        darkColor: '#4c566a'
        lightColor: '#d8dee9'
        lightestColor: '#eceff4'
        primaryColor: '#bf616a'
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
