baseURL: "https://blog.robnarok.de"
languageCode: "de"
title: "blog.robnarok.de"
paginate: 5
theme: gokarna
enableRobotsText: true
params:
  avatarURL: 'picture.jpg'
  avatarSize: ''
  description: 'robnarok'
  accentColor: '#FF4D4D'
  customHeadHTML: ''
  metaKeywords:
    - blog
    - hugo
  showPostsOnHomePage: 'recent'
  footer: 'Eigentlich hab ich nichts zu sagen. Aber das ist okay'
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: github
      url: 'https://github.com'
      weight: 3
