name: CI
on: push
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.93.3"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo -D
        
      - name: Clear old static files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ HOST.HOST }}
          USERNAME: ${{ HOST.USERNAME }}
          PORT: ${{ HOST.PORT }}
          KEY: ${{ HOST.SSHKEY }}
          script: rm /opt/website
        
      - name: Copy new static files
        uses: appleboy/scp-action@master
        env:
         HOST: ${{ HOST.HOST }}
         USERNAME: ${{ HOST.USERNAME }}
         PORT: ${{ HOST.PORT }}
         KEY: ${{ HOST.SSHKEY }}
        with:
         source: ".public"
         target: "/opt/website"
