name: CI
on:
  push:
    branches:
      - main
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - id: docker-publish
        uses: bitovi/github-actions-docker-publish@main
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
