name: CI
on:
  push:
    branches:
      - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.93.3"

      - name: Build
        run: hugo -D
        
      - name: Clean old static files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: rm -rf /opt/website/public
        
      - name: Copy new static files
        uses: appleboy/scp-action@master
        env:
         HOST: ${{ secrets.HOST }}
         USERNAME: ${{ secrets.USERNAME }}
         PORT: ${{ secrets.PORT }}
         KEY: ${{ secrets.SSHKEY }}
        with:
         source: "./public"
         target: "/opt/website/."
