name: CI
on:
  push:
    branches:
      - main
jobs:
 steps:
   - id: Docker Build Tag Publish
     uses: bitovi/github-actions-docker-publish@v1.0.7
     with:
        docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
